version: '3.9'

services:
  web:
    build: .
    container_name: gohcmc_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app           # Gắn code từ máy bạn vào container → không cần rebuild mỗi lần
    ports:
      - "8000:8000"
    env_file:
      - .env
